#!/bin/sh

### BEGIN INIT INFO
# Provides:          ivxx-hass
# Required-Start:    $local_fs $network 
# Required-Stop:     $local_fs $network 
# Default-Start:     S
# Default-Stop:      
# Short-Description: IVXX Hass
# Description:       IVXX implamentation of Home Assistant
### END INIT INFO


. /lib/lsb/init-functions
SCRIPT="/home/forsythc/virtualenvs/home-asssistant/bin/python3 /home/forsythc/virtualenvs/home-asssistant/bin/hass --open-ui"
RUNAS=forsythc

PIDFILE=/var/run/ivxx-hass.pid


case "$1" in
  start)
	log_begin_msg "Starting Home Assistant"
  	if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    		echo 'Service already running' >&2
    		return 1
 	fi
  	echo 'Starting service…' >&2
  	CMD="$SCRIPT & echo \$!"
  	su -c "$CMD" $RUNAS > "$PIDFILE"
  	echo 'Service started' >&2
	log_end_msg 0
	;;
  stop)
	if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
	  echo 'Service not running' >&2
	  return 1
	fi
	echo 'Stopping service…' >&2
	kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
	echo 'Service stopped' >&2

	;;
  restart)
	if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
	  echo 'Service not running' >&2
	  return 1
	fi
	echo 'Stopping service…' >&2
	kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
	echo 'Service stopped' >&2
  	if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    		echo 'Service already running' >&2
    		return 1
 	fi
  	echo 'Starting service…' >&2
  	local CMD="$SCRIPT & echo \$!"
  	su -c "$CMD" $RUNAS > "$PIDFILE"
  	echo 'Service started' >&2
	;;
  status)
	exit 0
	;;
  *)
	log_success_msg "Usage: /etc/init.d/ivxx-hass {start|stop|restart|status}"
	exit 1
esac

exit 0
